org: jhoganpachacutec
service: api-web-scraping-igp

provider:
  name: aws
  runtime: python3.13
  environment:
    TABLE_SISMOS: SismosIGP
  iam:
    role: arn:aws:iam::237501073282:role/LabRole

functions:
  fetchSismos:
    handler: fetchSismos.lambda_handler
    timeout: 29
    memorySize: 2048
    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:playwright-aws-lambda:28
    events:
      - http:
          path: igp/sismos
          method: get
          cors: true

resources:
  Resources:
    SismosIGP:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SismosIGP
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
